import Head from "next/head";
import React, { useState } from "react";
import Input from "src/components/Input";
import {
  useSearch,
  useOriginStations,
  useDestinationStations,
} from "src/hooks/queries";
import { searchRoute } from "src/lib/api";

export default function Home() {
  
  const [originId, setOriginId] = useState("");
  const [destinationId, setDestinationId] = useState("");
  const [date, setDate] = useState("");
  const [originSuggestions, setOriginSuggestions] = useState([]);

  const { searchResults, isError, error, search } = useSearch({
    originId,
    destinationId,
    date,
  });

  return (
    <div>
      <Head>
        <title>Trip Planner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center">
        <h1 className="text-2xl font-bold">Hey, Where you off to Next?</h1>
        <Input
          setOriginId={setOriginId}
          setDestinationId={setDestinationId}
          setDate={setDate}
          isLoading={false}
        />
        {/* <SearchResults searchResults={searchResults} /> */}
      </div>
    </div>
  );
}
